name: Update Version in README

on:
  push:
    paths:
      - 'version' # Triggers only when a file named 'version' in the root directory is modified

jobs:
  update-readme:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Read version from file
        id: read_version
        run: |
          # Reads the text inside the version file, cleans up whitespace, and stores it
          VAR_VERSION=$(cat version | xargs)
          echo "VERSION=$VAR_VERSION" >> $GITHUB_OUTPUT

      - name: Update version in README file
        run: |
          # Replaces the content inside <span id="version">...</span> with the new version value
          sed -i -E 's|<span id="version">[^<]*</span>|<span id="version">v1.2.1</span>|g' README.md

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          
          git add README.md
          
          if ! git diff --cached --quiet; then
            git commit -m "chore: update README version to ${{ steps.read_version.outputs.VERSION }} [skip ci]"
            git push origin HEAD:${{ github.event.repository.default_branch }}
          else
            echo "No changes to commit"
          fi
